name: Magisk Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "stub/**"
      - "buildSrc/**"
      - "build.py"
      - "gradle.properties"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: ubuntu-latest
    env:
      SCCACHE_DIRECT: false
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build release
        run: ./build.py -vr all

      - name: Build debug
        run: ./build.py -v all

      - name: Stop gradle daemon
        run: ./gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: out
          compression-level: 9

      - name: Setup Git
        run: git config --global user.email ${{ secrets.EMAIL }} && git config --global user.name pixincreate

      - name: Fetch commit hash and Magisk version
#        if: ${{ startsWith(github.event.head_commit.message, 'Release new canary build') }}
        run: |
          git fetch origin
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          
          echo "MAGISK_VERSION=$(grep 'magisk.versionCode=' gradle.properties | awk -F= '{print $2}')" >> $GITHUB_ENV
          echo "MAGISK_STUB_VERSION=$(grep 'magisk.stubVersion=' gradle.properties | awk -F= '{print $2}')" >> $GITHUB_ENV

      - name: Update configs
#        if: ${{ startsWith(github.event.head_commit.message, 'Release new canary build') }}
        run: |
          git checkout magisk-files
          echo "Updating Configs for the new release"
          
          jq --arg version "${COMMIT_HASH}" \
            --arg versionCode "${MAGISK_VERSION}" \
            --arg stubVersionCode "${MAGISK_STUB_VERSION}" \
            '.magisk.version = $version |
             .magisk.versionCode = $versionCode |
             .stub.versionCode = $stubVersionCode' canary.json > updated_canary.json
          mv updated_canary.json canary.json
          
          jq --arg version "${COMMIT_HASH}" \
            --arg versionCode "${MAGISK_VERSION}" \
            --arg stubVersionCode "${MAGISK_STUB_VERSION}" \
            '.magisk.version = $version |
             .magisk.versionCode = $versionCode |
             .stub.versionCode = $stubVersionCode' debug.json > updated_debug.json
          mv updated_debug.json debug.json
          
          git remote add upstream_server https://github.com/topjohnwu/magisk-files.git
          git fetch upstream_server
          git checkout upstream_server/canary notes.md
          
          echo -n "## Diffs to Official Magisk\nAdded support for GrapheneOS for personal use" >> notes.md
          
          git add canary.json debug.json notes.md

      - name: Download APKs
        #        if: ${{ startsWith(github.event.head_commit.message, 'Release new canary build') }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}

      - name: Upload Downloaded APKs to repo
        run: |
          git add app-debug.apk app-release.apk stub-debug.apk stub-release.apk
          git commit -m "Release new canary build ${COMMIT_HASH}"
          git push origin magisk-files
          
          git checkout master

      - name: Release APK
#        if: ${{ startsWith(github.event.head_commit.message, 'Release new canary build') }}
        uses: "dciborow/action-github-releases@v1.0.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.COMMIT_HASH }}
          prerelease: true
          title: "Magisk-v${{ env.COMMIT_HASH }}"
          files: |
            out/*.apk

      - name: Upload mapping and native debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-symbols
          path: app/build/outputs
          compression-level: 9

  test-build:
    name: Test building on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_DIRECT: false
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-14]
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build debug
        run: python build.py -v all

      - name: Stop gradle daemon
        run: ./gradlew --stop

  test:
    name: Test on API ${{ matrix.api }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        api: [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}
          path: out

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD test
        run: scripts/avd_test.sh ${{ matrix.api }}
